PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS cart(
    user_id INTEGER NOT NULL,
    book_id INTEGER NOT NULL,
    cart_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id)
);
CREATE TABLE IF NOT EXISTS last_search(
    user_id INTEGER NOT NULL,
    search TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS usename ON user (username);
CREATE UNIQUE INDEX IF NOT EXISTS id ON user (id);
CREATE UNIQUE INDEX IF NOT EXISTS cart_id ON cart (cart_id);
COMMIT;
